org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Minecraft / Fabric
minecraft_version=1.21.9
yarn_mappings=1.21.9+build.1
loader_version=0.19.2

# Mod metadata
mod_version=1.0.0
maven_group=com.abdy2.pathfindingx
archives_base_name=pathfinding-x

# Dependencies
fabric_version=0.133.14+1.21.9
kotlin_loader_version=1.13.11+kotlin.2.3.21
